-- Baseline do schema legado (nomes originais: needs / need_images).
-- A renomeação para campaigns ocorre na V2.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(255),
    data_nascimento DATE,
    telefone VARCHAR(255),
    whatsapp VARCHAR(255),
    cep VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(2),
    tipo VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    ativo BOOLEAN NOT NULL,
    data_cadastro TIMESTAMP
);

CREATE TABLE institution_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    razao_social VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),
    endereco VARCHAR(300),
    website VARCHAR(255),
    foto_url VARCHAR(500),
    descricao TEXT,
    categoria_atuacao VARCHAR(255),
    whatsapp VARCHAR(20),
    pix_key VARCHAR(100),
    pix_titular VARCHAR(100),
    aprovado BOOLEAN NOT NULL,
    data_cadastro TIMESTAMP,
    motivo_recusa TEXT,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE needs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instituicao_id BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    categoria VARCHAR(255),
    quantidade_alvo VARCHAR(255) NOT NULL,
    urgencia VARCHAR(255),
    aceita_financeiro BOOLEAN,
    progresso INTEGER,
    ativo BOOLEAN NOT NULL,
    data_criacao TIMESTAMP,
    data_encerramento TIMESTAMP,
    CONSTRAINT fk_need_institution FOREIGN KEY (instituicao_id) REFERENCES institution_profiles (id)
);

CREATE TABLE need_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    need_id BIGINT NOT NULL,
    filename VARCHAR(200) NOT NULL,
    legenda VARCHAR(200),
    ordem INTEGER,
    data_upload TIMESTAMP,
    CONSTRAINT fk_image_need FOREIGN KEY (need_id) REFERENCES needs (id) ON DELETE CASCADE
);

CREATE TABLE donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id BIGINT NOT NULL,
    necessidade_id BIGINT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    item VARCHAR(255) NOT NULL,
    quantidade VARCHAR(255) NOT NULL,
    categoria VARCHAR(255),
    observacao TEXT,
    status VARCHAR(255) NOT NULL,
    data_intencao TIMESTAMP,
    data_recebimento TIMESTAMP,
    CONSTRAINT fk_donation_doador FOREIGN KEY (doador_id) REFERENCES users (id),
    CONSTRAINT fk_donation_need FOREIGN KEY (necessidade_id) REFERENCES needs (id)
);

CREATE TABLE donation_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL,
    mensagem TEXT NOT NULL,
    foto_url VARCHAR(500),
    data_criacao TIMESTAMP,
    CONSTRAINT fk_update_donation FOREIGN KEY (donation_id) REFERENCES donations (id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    doador_id BIGINT NOT NULL,
    instituicao_id BIGINT NOT NULL,
    necessidade_id BIGINT,
    valor NUMERIC(10, 2) NOT NULL,
    metodo VARCHAR(20) NOT NULL,
    status VARCHAR(255) NOT NULL,
    comprovante_url VARCHAR(500),
    transacao_id VARCHAR(100),
    data_criacao TIMESTAMP,
    data_confirmacao TIMESTAMP,
    CONSTRAINT fk_payment_doador FOREIGN KEY (doador_id) REFERENCES users (id),
    CONSTRAINT fk_payment_instituicao FOREIGN KEY (instituicao_id) REFERENCES institution_profiles (id),
    CONSTRAINT fk_payment_need FOREIGN KEY (necessidade_id) REFERENCES needs (id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    mensagem VARCHAR(300) NOT NULL,
    link VARCHAR(200),
    lida BOOLEAN NOT NULL,
    data_criacao TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (usuario_id) REFERENCES users (id)
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(100) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL,
    CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL,
    assunto VARCHAR(200),
    mensagem TEXT NOT NULL,
    lido BOOLEAN NOT NULL,
    data_envio TIMESTAMP
);

CREATE TABLE blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    slug VARCHAR(80) NOT NULL UNIQUE,
    conteudo TEXT NOT NULL,
    resumo VARCHAR(300),
    autor_id BIGINT NOT NULL,
    categoria VARCHAR(255),
    imagem_url VARCHAR(500),
    publicado BOOLEAN NOT NULL,
    data_criacao TIMESTAMP,
    data_publicacao TIMESTAMP,
    CONSTRAINT fk_post_autor FOREIGN KEY (autor_id) REFERENCES users (id)
);
