-- Marketplace reverso: doador oferta item; instituição reivindica e coleta em prazo.
CREATE TABLE ofertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    categoria VARCHAR(255),
    estado_item VARCHAR(50),
    cidade VARCHAR(255),
    precisa_coleta BOOLEAN NOT NULL DEFAULT FALSE,
    endereco_coleta VARCHAR(300),
    disponivel_ate DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    instituicao_id BIGINT,
    reservada_em TIMESTAMP,
    prazo_coleta DATE,
    data_entrega TIMESTAMP,
    data_criacao TIMESTAMP,
    CONSTRAINT fk_oferta_doador FOREIGN KEY (doador_id) REFERENCES users (id),
    CONSTRAINT fk_oferta_instituicao FOREIGN KEY (instituicao_id) REFERENCES institution_profiles (id)
);

CREATE TABLE oferta_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oferta_id BIGINT NOT NULL,
    filename VARCHAR(200) NOT NULL,
    legenda VARCHAR(200),
    ordem INTEGER,
    data_upload TIMESTAMP,
    CONSTRAINT fk_oferta_image FOREIGN KEY (oferta_id) REFERENCES ofertas (id) ON DELETE CASCADE
);
